TeamDATEROAD/DATEROAD-ANDROID

- app/src/main/java/org/sopt/dateroad/presentation/ui/component/tabbar/DateRoadTabBar.kt
- closed #12 
- TabBar 컴포넌트를 구현했어요
https://github.com/TeamDATEROAD/DATEROAD-ANDROID/assets/103172971/9885c420-3974-499b-9511-c4ed71e96377
- N/A
얘들아 힘들면 힘들다구 말해,, ㅠㅠ
자고 싶으면 잔다고 말해!! 걱정된다능,,
> [feat] TabBar 컴포넌트

- app/src/main/java/org/sopt/dateroad/domain/model/MainDate.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadDateSchedulekt.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeTimeLineCard.kt
- app/src/main/res/drawable/ic_home_plus_purple.xml
- app/src/main/res/values/strings.xml
- closed #36 
- DateSchedule 컴포넌트 구현
- N/A
> [feat] DateSchedule 컴포넌트 구현

- app/src/main/java/org/sopt/dateroad/domain/model/Course.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadCourseCard.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadCourseCardColumn.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeHotCourseCard.kt
- closed #48 
- DateRoadCourseCardColumn 컴포넌트 구현
- N/A
> [feat] CourseCard Column 컴포넌트 구현

- app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollSecondScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/util/draganddrop/DragAndDropListState.kt
- app/src/main/java/org/sopt/dateroad/presentation/util/lazylist/LazyListExt.kt
- app/src/main/java/org/sopt/dateroad/presentation/util/mutablelist/MutableListExt.kt
- closed #90 
- 코스 등록 뷰의 Drag and Drop 기능을 구현하였습니다.
https://github.com/user-attachments/assets/ca427b67-e2fa-4e36-ac26-4e9c97503ab4
- N/A
배지현 뷰 작업 진짜 끝입니다용
> [feat] 코스 등록 Drag and Drop

- app/build.gradle.kts
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
- gradle/libs.versions.toml
- closed #103 
- 접근 권한이 없을 때 이미지 스크롤 막기
- N/A
뷰 찐찐찐 막!
> [feat] Course Detail View Scroll 막기

- app/src/main/java/org/sopt/dateroad/data/dataremote/interceptor/AuthInterceptor.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
- closed #123 
- 데이트 코스 삭제 API를 연동하였습니다
[화면 기록 2024-07-17 오
https://github.com/user-attachments/assets/81bf48d3-4681-40ef-b851-d86bdcc41a6e
뒤로 가기 추가 구현해서 푸시하겠습니당
-> 이거 추가했습니다!
> [feat] 데이트 코스 삭제 API 연동 

- app/src/main/java/org/sopt/dateroad/data/dataremote/datasource/AuthRemoteDataSource.kt
- app/src/main/java/org/sopt/dateroad/data/dataremote/datasourceimpl/AuthRemoteDataSourceImpl.kt
- app/src/main/java/org/sopt/dateroad/data/dataremote/interceptor/AuthInterceptor.kt
- app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestWithdrawDto.kt
- app/src/main/java/org/sopt/dateroad/data/dataremote/service/AuthService.kt
- app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
- app/src/main/java/org/sopt/dateroad/data/repositoryimpl/AuthRepositoryImpl.kt
- app/src/main/java/org/sopt/dateroad/di/DataSourceModule.kt
- app/src/main/java/org/sopt/dateroad/di/RepositoryModule.kt
- app/src/main/java/org/sopt/dateroad/di/ServiceModule.kt
- app/src/main/java/org/sopt/dateroad/domain/repository/AuthRepository.kt
- app/src/main/java/org/sopt/dateroad/domain/type/MoneyTagType.kt
- app/src/main/java/org/sopt/dateroad/domain/usecase/DeleteWithdrawUseCase.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadBasicButton.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadTwoButtonDialog.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadTwoButtonDialogWithDescription.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/navigation/MyPageNavigation.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
- app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
- closed #129 
- 유저 탈퇴 API 구현
유저 3,4번 두 개라 서버가 함부러 지우지 말래요!
그래서 2번넣고 에러라도 받아볼라했는데 로그가 안찍히넹 엄마 낼봐!
> [feat] 유저 탈퇴 API 연동

- app/src/main/java/org/sopt/dateroad/data/dataremote/model/request/RequestUsePointDto.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeTimeLineCard.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
- closed #137 
- 
- 이미지가 위로 스크롤 되지 않았을 때 탑바 배경에 gradient 값 부여
- 포인트를 사용해 코스를 열람했 을 때 확인버튼 누르면 다이얼로그 visible false
https://github.com/user-attachments/assets/c53765ea-2273-4821-8371-bd293952044c
- N/A
혹시 탑바 graident alpha값이 작아서 잘 안보이면 말해주세요! 더 어둡게 수정하곘습니다
> [refactor] 코스 상세 UI & 열람 로직 수정

- app/src/main/java/org/sopt/dateroad/presentation/ui/component/webview/DateRoadWebView.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/signin/SignInScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
- closed #140 
- 문의하기 노션 웹뷰 연결
- 포인트 제도 화면연결
https://github.com/user-attachments/assets/0a863362-8022-411c-b168-99f448e10f9a
- N/A
한 번 할때 꼼꼼히 할걸!
> [refactor] My Page View 포인트 제도 화면 연결 & 노션 웹뷰 연결

- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeViewModel.kt
- closed #156 
- Home View SideEffect 적용
N/A
N/A
N/A
> [refactor] Home View SideEffect 적용

- app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadBasicBottomSheet.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadBottomSheet.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadImageButton.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/navigation/TimelineDetailNavigation.kt
- closed #153 
- Button 활성화 리팩토링
- N/A
에뮬레이터 안돌아가서.. 확인 불가능 ㅠㅠ... 확인 좀 해주세요
> [refactor] Button 활성화 리팩토링

- app/build.gradle.kts
- app/src/main/java/org/sopt/dateroad/data/dataremote/service/AuthService.kt
- app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDetailDtoMapper.kt
- app/src/main/java/org/sopt/dateroad/domain/type/MoneyTagType.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/card/DateRoadPlaceCard.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadErrorView.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollSecondScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/component/TimelineCard.kt
- gradle/libs.versions.toml
- closed #159 
- 안드 자체 QA 사항을 반영하였습니다.
자잘자잘하게 바뀌어서 영상 생략할게요
- N/A
이제 큐에이!
> [refactor] 안드 자체 QA 사항 반영

- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/component/HomeTimeLineCard.kt
- closed #162
- 광고 배너 패딩값 수정
- 코스 상세 전체 비용 폰트 변경 사항 적용
- 타임라인 카드 horizontal 가운데 정렬 제거
- N/A
> [refactor] 전체 QA 사항 반영

- app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
- closed #167 
- 화면전환이 여러번 발생해도 스택 관리를 통해 뒤로가기를 하면 홈화면으로 이동합니다
https://github.com/user-attachments/assets/17b2c376-5ae5-4561-8066-580a5ca515f0
더 여러가지 상황에서 스택처리 어떻게 할지 같이 찾아봐요 ㅋㅋ
엄마 이슈 뻇을게~
> [refactor] 백스택 관리

- app/src/main/java/org/sopt/dateroad/presentation/type/OneButtonDialogWithDescriptionType.kt
- app/src/main/java/org/sopt/dateroad/presentation/type/ProfileType.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/component/dialog/DateRoadDialog.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/MyPageViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/mypage/navigation/MyPageNavigation.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileContract.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/profile/navigation/ProfileNavigation.kt
- app/src/main/res/values/strings.xml
- closed #170 
- 추후 공개될 예정이었던 프로필 변경 기능 View 구현
- ProfileType을 제작하여 기존 Profille Screen 재사용
- ProfileType을 통한 분기처리
https://github.com/user-attachments/assets/aeedae8a-19c7-41c9-8666-374b18cab593
서버만 붙이면 기존 프로필 받아오고 변경도 잘 돌아가겠죠?
> [feat] 프로필 수정 View 구현

- app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/CostMapper.kt
- app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDetailDtoMapper.kt
- app/src/main/java/org/sopt/dateroad/domain/model/CourseDetail.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailInfoBar.kt
- closed #168 
- 일반 함수로 Screen에서 처리했던 금액 태그와 실제 금액 String을 구분여 Mapper 처리
- N/A
시간에 쫓겨서 급하게 짠 별로인 코드 고쳐나갈게요 ㅎ
> [refactor] 금액 String Mapper 수정

- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
- closed #190 
- 티켓과 흰색 박스 사이 간격 조절
- N/A
> [refactor] Home 화면 디자인 변경 적용

- app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseTimelineDetailDtoMapper.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
- app/src/main/res/values/strings.xml
- closed #192 
- 데이트 코스 상세 시작 시간 형식 변경
- N/A
> [refactor] 데이트 코스 상세 시작 시간 형식 변경

- app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt
- app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/PointMapper.kt
- app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponsePointDtoMapper.kt
- app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponsePointHistoryDtoMapper.kt
- app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponsePointsDtoMapper.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/PointHistoryViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/pointhistory/component/PointHistoryCard.kt
- app/src/main/res/values/strings.xml
- closed #205 
- 포인트 내역 (PointHistory) 뷰의 자체 QA 사항을 반영하였습니다.
- 닉네임 뒤 공백 제거
- 포인트 내역 앞 +, - 추가
https://github.com/user-attachments/assets/116e0839-c766-44a8-9cab-735c7e7ce630
- N/A
하 난 왜 맨날 벼락치기를 할까
> [chore] 자체 QA - 포인트 내역 (PointHistory) 뷰

- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileViewModel.kt
- closed #209
- 코스 등록 + 일정 등록 (Enroll) 뷰의 자체 QA 사항을 반영합니다.
- 불러온 상태에서 코스 및 일정 등록 시 StartAt 뒤 "시작" 제거
- 일정 등록 - 불러오기 버튼 오른쪽 마진 값 수정
- 일정 등록 - 불러오기 방문일자 미선택 시 버튼 비활성화
https://github.com/user-attachments/assets/5a932930-2c4b-4c74-bd27-c71f096b92dd
- N/A
아 분명 했던 것 같은데
> [chore] 자체 QA - 코스 등록 + 일정 등록 (Enroll) 뷰

- app/src/main/java/org/sopt/dateroad/presentation/ui/component/bottomsheet/DateRoadRegionBottomSheet.kt
- closed #213 
- 코스 둘러보기 (Look) 뷰의 자체 QA 사항을 반영했어요.
- 지역 바텀시트 적용하기 버튼 가운데 정렬
https://github.com/user-attachments/assets/b2fb89fd-50cd-4344-abde-2e058023b5cc
- N/A
ㅠㅠ
> [chore] 자체 QA - 코스 둘러보기 (Look) 뷰

- app/src/main/java/org/sopt/dateroad/presentation/type/TagType.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt
- closed #222 
- HOT 데이트 코스 LazyLow 수정
- N/A
죽은 줄 알았지~? 돌아왔지롱
> [fix] HOT 데이트 코스 LazyLow 수정

- app/src/main/res/values/strings.xml
- closed #241
-  신고 팝업 멘트 수정
- 코스 상세 포인트로 열람하기 모달 텍스트 수정
코스 상세 열람 모달은 현재 무료 기회가 차감 안되는 이슈로 찍지 못했습니다...
N/A
배고프다
> [chore] 텍스트 변경사항 적용 

- app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
- app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
- closed #253 
- 닉네임이 전부 지워지지 않는 문제를 해결하였습니다.
https://github.com/user-attachments/assets/2bd33080-6e80-435a-b0b1-2c56fe43d273
- N/A
죄송합니다 ㅠㅠ 공백인 상태를 고려 못 함 ㅜㅜ
> [fix] 닉네임이 전부 지워지지 않는 문제 해결

- app/build.gradle.kts
- app/src/main/java/org/sopt/teamdateroad/presentation/ui/enroll/EnrollScreen.kt
- gradle/libs.versions.toml
- closed #282 
- 일정 등록하기 두 번째 뷰에 존재하던 불러오기 버튼 삭제
https://github.com/user-attachments/assets/4afbd7fb-a08e-46c8-a2d6-adf4aa9016f9
- N/A
pr 오랜만이긔
> [fix] 코스 입력 뷰에서 불러오기 시 입력한 날짜가 사라지는 이슈 해결 
