TeamDATEROAD/DATEROAD-ANDROID

app/src/main/java/org/sopt/dateroad/presentation/type/PointBoxType.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/dummy/DummyScreen.kt, app/src/main/java/org/sopt/dateroad/ui/theme/Color.kt, app/src/main/java/org/sopt/dateroad/ui/theme/Theme.kt, app/src/main/java/org/sopt/dateroad/ui/theme/Type.kt
- closed #17 
- Theme 기초 세팅을 진행하였어요.
이런 식으로 사용하시면 됩니다.
- N/A
기본 배경색을 바꾸고 싶은데 아시는 분 있나요? ㅠ 죽어도 안 됨
=> [init] Theme 기초 세팅

app/src/main/java/org/sopt/dateroad/domain/model/Course.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadCourseCard.kt
- closed #34 
- Course Card 컴포넌트 구현
- N/A
부족하지만 예쁘게 봐주세용 ><
=> [feat] Course Card 컴포넌트 구현

app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadChip.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadImageChip.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/component/chip/DateRoadTextChip.kt
- closed #45 
- 원래 String 안에 포함되어 있던 아이콘을 디자인 변경에 따른 Image로 적용
- 없습니다!
=> [refactor] Chip 아이콘 String -> Image

app/src/main/java/org/sopt/dateroad/domain/model/Advertisement.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/DateRoadAdvertisement.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/component/item/HomeAdvertisement.kt
- closed #50 
- Advertisement 컴포넌트 구현
- N/A
=> [feat] Advertisement 컴포넌트 구현

app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadAreaButton.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/look/LookScreen.kt
- closed #76 
- 코스 둘러보기 (Look) 뷰에 있는 지역 버튼의 디자인을 변경하였습니다.
https://github.com/TeamDATEROAD/DATEROAD-ANDROID/assets/103172971/0f1a920c-80ef-4f01-8d9b-ef653bb3e17d
- N/A
디자인 반영 끝!
=> [fix] 코스 둘러보기 (Look) 뷰 지역 버튼 디자인 변경

app/src/main/java/org/sopt/dateroad/data/mapper/toEntity/AreaMapper.kt, app/src/main/java/org/sopt/dateroad/data/mapper/todata/EnrollMapper.kt, app/src/main/java/org/sopt/dateroad/data/repositoryimpl/CourseRepositoryImpl.kt, app/src/main/java/org/sopt/dateroad/domain/type/SeoulAreaType.kt, app/src/main/java/org/sopt/dateroad/domain/util/Constraints.kt
- closed #195 
- 변경된 지역 필터 값을 반영했어요.
- 지역 관련 API 통신에서 Enum이 사용되는 부분을 한글로 변경하였어요.
- 데이트 코스 전체 조회 API
-  데이트 코스 등록 API
-  데이트 일정 등록 API 
[코스 둘러보기]
https://github.com/user-attachments/assets/c20d713e-d833-40e0-8294-74b2ce216e11
[데이트 코스 등록]
https://github.com/user-attachments/assets/289dec11-4cd6-4231-8126-77dff8078e6c
[데이트 일정 등록]
https://github.com/user-attachments/assets/e5b54a3e-49b9-45a5-9d18-070051f579db
- N/A
- 에러 발생하는 부분 디코에 남겨두었어요 - 서버와 논의 중 (데이트 일정 등록 API (api/v1/dates)에서 변경된 지역 값으로 데이트 일정 등록 요청 시 서버 에러 발생)
- 얘들아 늦게 해서 미안해 ㅠㅠ
=> [chore] 지역 관련 API 통신 Enum -> 한글 변경

app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseCourseDetailDtoMapper.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailOpenedDetail.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/component/CourseDetailTimeline.kt
- closed #201 
- Dto Mapper 수정
- 코스 상세 뷰 시작시간 추가
[시작 시간 추가 전]
[시작 시간 추가 후]
- N/A
현진이꺼 참고하니까 금방했어요!
=> [refactor] 코스 상세 뷰 시작시간 정보 추가 

app/src/main/java/org/sopt/dateroad/presentation/ui/onboarding/OnboardingScreen.kt, app/src/main/res/values/strings.xml
- closed #203
- PartialColorText 키워드 수정
- description 줄바꿈 적용
https://github.com/user-attachments/assets/b50c7861-50aa-4e3a-9c38-f018a1517a92
- N/A
2시간 반 남았다 ㅎㅎ
=> [chore] 온보딩 뷰 디자인 수정

app/src/main/java/org/sopt/dateroad/data/dataremote/util/Constraints.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/component/card/DateRoadCourseCard.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/component/tag/DateRoadPointTag.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeContract.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/home/component/HomeAdvertisement.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/home/component/HomeTopBar.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
- closed #217 
- 프로필 기본이미지 -> 실제 프로필 이미지
- 다가오는 데이트 > 클릭 시 해당 데이트 상세 페이지로 이동 
- 광고 배너 비율 조정
- HOT 데이트 코스 오른쪽 마진 없도록 설정
- 0 시간 (전체적으로) 공백 삭제 -> 0시간
- 데이트 코스 카드 minLines속성 추가 (2줄)
실제 프로필 이미지
데이트 상세 페이지로 이동
https://github.com/user-attachments/assets/65c27c9c-5d28-4159-a484-75d5352949a1
광고 배너 비율
Hot 데이트 코스 오른쪽 패딩 제거
시간 숫자, 텍스트 사이 공백 제거
데이트 카드 minLines 속성 추가 및 2로 설정
와 6시 반 전에 끝냈네 그래도 힣
=> [chore] 자체 QA - 홈(Home) 뷰

app/src/main/java/org/sopt/dateroad/data/mapper/todomain/ResponseTimelineDtoMapper.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/past/PastScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/past/component/PastCard.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/TimelineScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/component/TimelineCard.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt, app/src/main/res/drawable/bg_past_card.xml, app/src/main/res/drawable/bg_timeline_detail.xml
- closed #215 
- Timeline 관련 뷰 (데이트 일정, 지난 데이트, 데이트 상세)의 자체 QA 사항을 반영했어요.
- 데이트 일정 - 지역 태그
- 지난 데이트 - 엠티뷰 가운데 정렬
- 지난 데이트 - 지역 태그
- 지난 데이트 - ➰ 이미지
- 데이트 상세 - ➰ 이미지
https://github.com/user-attachments/assets/8a7d792d-8d18-41cf-accb-bea6f5757eca
- N/A
마지막!! 끝났당 ㅋㅋ
=> [chore] 자체 QA - Timeline 관련 뷰 (데이트 일정, 지난 데이트, 데이트 상세)

app/src/main/java/org/sopt/dateroad/data/mapper/todata/PlaceMapper.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollViewModel.kt
- closed #220
- 코스 불러오기를 통한 코스 등록이 되지 않는 문제를 해결합니다.
N/A
- N/A
시간 앞의 공백을 제거하면서 Place 매퍼를 변경하지 않아서 발생한 문제였어요 ㅠㅠ
죄송합니다 ㅠㅠ
=> [hotfix] 코스 불러오기를 통한 코스 등록이 안 되는 문제 해결

app/src/main/java/org/sopt/dateroad/presentation/ui/component/button/DateRoadButton.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/util/modifier/ModifierExt.kt
- closed #226 
- 버튼이 중복 클릭되는 문제를 해결하였습니다.
https://github.com/user-attachments/assets/a00004c7-4ca9-4e2f-89f0-58052ac8decb
아무튼 연속 클릭 하고 있는 거임,,!
- N/A
1. noRippleDebounceClickable에 suspend 추가
기존에 0.5초의 딜레이를 주어 중복 클릭을 막아두었지만, 서버 통신에서 0.5초 이상의 시간이 걸리는 경우 (멀티파트라 아무래도 오래 걸리는 듯요 ㅠㅠ) 요청이 여러 번 가는 문제를 확인했습니다. 그래서 Clickable 함수에 suspend를 추가하고 로직을 일부 수정하여 **서버통신 완료 후** 0.5초의 딜레이를 주는 것으로 로직을 변경하였습니다.
2. EnrollScreen에 LodingView 추가
EnrollScreen에 로딩뷰를 추가해두지 않아 중복 클릭의 위험이 더 증가한다고 판단하였습니다. 따라서 이를 방지하고자 (+ 다른 뷰와의 통일성을 유지하고자) EnrollScreen에 로딩뷰를 추가하였습니다.
=> [fix] 버튼 중복 클릭 문제 해결

app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseContract.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/MyCourseScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/mycourse/navigation/MyCourseNavigation.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt
- closed #230 
- 내가 등록한 코스에서 아이템 클릭 시 코스 상세 페이지로 이동할 수 있는 기능을 구현합니다.
https://github.com/user-attachments/assets/3e9f7c4f-478a-4da7-981a-50517e94c47f
- N/A
스택 관리는 스택 관리 이슈에서 한 번에 진행할게요.
=> [feat] 내가 등록한 코스 -> 코스 상세 페이지 이동 기능 구현

app/src/main/java/org/sopt/dateroad/presentation/ui/home/HomeScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/home/navigation/HomeNavigation.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/MainNavigator.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/timeline/navigation/TimelineNavigation.kt
- closed #232 
- 홈 뷰에서 더보기를 통한 바텀 네비 이동 시 스택이 쌓여 바텀 네비가 동작하지 않는 문제를 해결했습니다.
https://github.com/user-attachments/assets/c7c37248-4216-4e9a-8dfa-5b9801b81f17
- N/A
바텀 네비에 있는 뷰로 화면 전환을 할 때는 바텀 네비를 전환시키는 함수 (navigateMainNavigation)를 사용하여야 하는데 그걸 안 사용하고 일반적으로 뷰를 전환하는 로직을 사용해 화면 전환을 구현하였더라구요 ㅠㅠ (왜 그랬지 ㅜㅜ) navigateMainNavigation을 활용하는 방식으로 수정했는데 혹시 또 바텀 네비 스택 관리가 안 되는 부분이 발견되면 말씀해주세용
=> [fix] 더보기를 통한 이동 시 스택이 쌓이는 문제 해결

app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt, app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
- closed #236 
-포인트 사용 [유저 데이트 코스 열람] API의 description을 변경합니다.
- N/A
지금,, 무료 열람 기회 차감이 안 되고 있어서 포인트 내역 (PointHistory) 뷰에서 잘 반영이 되었는지는 확인을 못 했어요,,! 서버 측에 얘기해놓은 상태이고 해결되면 스크린샷 업데이트 하도록 하겠습니다.
-> 반영 완 ~
=> [chore] 포인트 사용 [유저 데이트 코스 열람] API description 변경

app/src/main/java/org/sopt/dateroad/data/dataremote/interceptor/AuthInterceptor.kt
- closed #204 
- 리이슈 중복 호출 후 마지막 호출에 의한 통신만 재전송하는 문제를 해결하였습니다.
- N/A
1. 토큰 재발급 중복 호출 문제를 해결하였습니다.
- 기존에는 AtomicBoolean을 이용하였는데 Mutex를 이용하는 방식으로 수정하였습니다. (동시성 문제는 보통 Mutex를 이용해 해결한다고 하더라구요 엄마 체고 ㅠ)
Mutex에 lock을 걸어서 한 번에 하나의 재발급 요청이 이루어지도록 하였습니다. (이전 재발급 요청이 완료되지 않은 경우 재발급 요청을 보내지 못하도록 구현)
- 재발급이 완료된 후 새로운 액세스 토큰이 아닌 기존의 액세스 토큰을 이용해 요청을 보내는 경우 (현재 로컬에 저장된 액세스 토큰과 요청을 보낼 때 사용되는 액세스 토큰 값이 다른 경우) 현재 로컬에 저장된 액세스 토큰으로 새로운 리퀘스트를 만들어 요청을 보내도록 하였습니다.
=> [fix] 리이슈 중복 호출 후 마지막 호출에 의한 통신만 재전송하는 문제 해결

app/src/main/java/org/sopt/dateroad/data/mapper/todata/EnrollMapper.kt, app/src/main/java/org/sopt/dateroad/data/repositoryimpl/CourseRepositoryImpl.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/component/view/DateRoadLoadingView.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/EnrollScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/profile/ProfileScreen.kt
- closed #270 
- 2차 QA사항을 반영합니다.
- N/A
-
=> [fix] 2차 QA사항 반영

.github/workflows/android_ci.yml, app/build.gradle.kts, app/proguard-rules.pro, gradle/libs.versions.toml
- closed #269 
- 릴리즈를 위한 준비를 하였습니다.
N/A
- N/A
불필요한 코드 삭제는 따로 이슈 파서 진행할게요
=> [feat] 릴리즈 준비

app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailContract.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/coursedetail/CourseDetailViewModel.kt, app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
- closed #263 
- 코스 상세 뷰의 앰플리튜드 트래킹 이벤트 코드를 심었어요!
-  view_course_details
- click_course_back
- click_course_likes
view_course_details 이벤트
click_course_back 이벤트
click_course_likes 이벤트
- N/A
유저 프로퍼티 빼고 다 컷! ㅋㅋ
=> [feat] 코스 상세 뷰 앰플리튜드 트래킹 이벤트 코드 심기

app/src/main/java/org/sopt/dateroad/presentation/ui/navigator/component/MainNavHost.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/TimelineDetailScreen.kt, app/src/main/java/org/sopt/dateroad/presentation/ui/timelinedetail/navigation/TimelineDetailNavigation.kt, app/src/main/java/org/sopt/dateroad/presentation/util/Constraints.kt
- closed #256 
- 데이트 일정 뷰의 앰플리튜드 트래킹 이벤트 코드를 심었습니다.
- view_schedule_details
- click_kakao_share
- click_close_kakao
- click_open_kakao
유입경로 Home일 때
유입경로 Timeline일 때
- N/A
뷰 유입 경로는 전체적인 네비게이션을 손봐야 할것 같아서 일단 Test Value 전송하는데 다른 방법 있나요...??
-> 해결 완!
=> [feat] 데이트 일정 상세 뷰 앰플리튜드 트래킹 이벤트 코드 심기
